#!/bin/sh

# get private IP address
# used for outgoing Internet connections
# see: https://github.com/rsp/scripts/blob/master/privateip.md

[ -n "$1" ] && t=$1 || t='8.8.8.8'

ip route get $t | awk '{print $NF; exit}'

